version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/chatham/api/v2/package
  api_key:
    secure: Zj8bjUB0ykUgS7wA0QDyQcxxKE4nd3lXtEkh3MRTELjGByXUb4P4x9+h2iGTNui1
  skip_symbols: true
  on:
    branch: master
# - provider: NuGet
#   name: production
#   api_key:
#     secure:
#   on:
#     branch: master
#     appveyor_repo_tag: true
